In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
dataset = pd.read_csv('Place.csv')
dataset

Coding Skills   Aptitude Skills  Technical Skills   Communication Skills  \
0                85               85                 90                    30   
1                89               90                 85                    35   
2                80               85                 90                    45   
3                95               90                 90                    20   
4                95               85                 80                    75   
..              ...              ...                ...                   ...   
118              58               59                 68                    59   
119              59               58                 62                    58   
120              66               52                 68                    54   
121              62               65                 62                    55   
122              64               64                 61                    52   

     Core Knowledge  Presentation Skills  Academic Performance  \
0                40                   40                    75   
1                50                   35                    70   
2                55                   45                    78   
3                40                   30                    60   
4                80                   80                    88   
..              ...                  ...                   ...   
118              79                   57                    74   
119              80                   59                    78   
120              84                   58                    50   
121              81                   56                    78   
122              80                   41                    50   

     Puzzle Solving skills  English Proficiency  Programming Skills  \
0                       75                   50                  90   
1                       80                   40                  80   
2                       85                   55                  88   
3                       80                   30                  80   
4                       90                   80                  85   
..                     ...                  ...                 ...   
118                     84                   60                  58   
119                     86                   59                  57   
120                     78                   58                  59   
121                     49                   54                  58   
122                     74                   57                  54   

     Management Skills  Projects  Internships  Training  Backlog   Placed  
0                   40        80           80        85        0       52  
1                   40        70           75        80        0       44  
2                   45        85           80        80        0       60  
3                   30        70            0         0        0       30  
4                   70        90           80        80        0       95  
..                 ...       ...          ...       ...      ...      ...  
118                 64        49           47        68        0       85  
119                 65        48           48        64        1       75  
120                 63        46           47        64        2       64  
121                 64        45           49        61        0       66  
122                 65        41           51        52        1       74  

[123 rows x 16 columns]

In [33]:
dataset.dtypes

Coding Skills            int64
Aptitude Skills          int64
Technical Skills         int64
Communication Skills     int64
Core Knowledge           int64
Presentation Skills      int64
Academic Performance     int64
Puzzle Solving skills    int64
English Proficiency      int64
Programming Skills       int64
Management Skills        int64
Projects                 int64
Internships              int64
Training                 int64
Backlog                  int64
 Placed                  int64
dtype: object

In [39]:
# dataset.loc[dataset[' Placed'] > 49, ' Placed'] = 1 DIDN'T WORK
# dataset.loc[dataset[' Placed'] < 50, ' Placed'] = 0 DIDN'T WORK

# dataset[' Placed'] = np.where(dataset[' Placed'] > 49, 1, dataset[' Placed']) WORKED
# dataset[' Placed'] = np.where(dataset[' Placed'] != 1, 0, dataset[' Placed']) WORKED
dataset.head(20)

Coding Skills   Aptitude Skills  Technical Skills   Communication Skills  \
0               85               85                 90                    30   
1               89               90                 85                    35   
2               80               85                 90                    45   
3               95               90                 90                    20   
4               95               85                 80                    75   
5               90               75                 80                    78   
6               70               79                 80                    78   
7               50               65                 70                    75   
8               60               75                 74                    60   
9               90               91                 85                    71   
10              70               82                 69                    85   
11              94               97                 91                    93   
12              55               89                 65                    80   
13              88               90                 80                    86   
14              45               72                 72                    68   
15              49               70                 65                    55   
16              51               74                 60                    55   
17              65               70                 60                    55   
18              85               70                 65                    60   
19              40               70                 70                    70   

    Core Knowledge  Presentation Skills  Academic Performance  \
0               40                   40                    75   
1               50                   35                    70   
2               55                   45                    78   
3               40                   30                    60   
4               80                   80                    88   
5               85                   84                    76   
6               60                   47                    78   
7               65                   65                    74   
8               70                   75                    80   
9               65                   80                    79   
10              73                   82                    79   
11              90                   94                    90   
12              75                   80                    75   
13              81                   82                    81   
14              45                   55                    55   
15              50                   60                    74   
16              40                   60                    50   
17              50                   40                    65   
18              60                   70                    80   
19              75                   80                    65   

    Puzzle Solving skills  English Proficiency  Programming Skills  \
0                      75                   50                  90   
1                      80                   40                  80   
2                      85                   55                  88   
3                      80                   30                  80   
4                      90                   80                  85   
5                      84                   87                  83   
6                      60                   70                  70   
7                      75                   80                  65   
8                      60                   74                  70   
9                      85                   84                  90   
10                     79                   83                  72   
11                     93                   91                  94   
12                     83                   71 

In [40]:
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values
print(X)
print(Y)

[[85 85 90 ... 80 85  0]
 [89 90 85 ... 75 80  0]
 [80 85 90 ... 80 80  0]
 ...
 [66 52 68 ... 47 64  2]
 [62 65 62 ... 49 61  0]
 [64 64 61 ... 51 52  1]]
[1 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 1 1 1 1 1 1 1 1 1 1]


In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)
X_train.shape, X_test.shape

((86, 15), (37, 15))

In [47]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(random_state=42, n_jobs=-1, max_depth=5, n_estimators=100, oob_score=True)
regressor.fit(X_train, Y_train) 

RandomForestRegressor(max_depth=5, n_jobs=-1, oob_score=True, random_state=42)

In [54]:
dataset.head()
place_predict = regressor.fit(X_train, Y_train)

In [55]:
place_predict.predict([[100,100,100,100,100,100,100,100,100,100,100,100,100,100,100]])

array([0.97])

In [56]:
import pickle as pk
file = pk.dump(place_predict, open('place_predict.pkl', 'wb'))

In [58]:
model = pk.load(open('place_predict.pkl', 'rb'))
model.predict([[100,100,100,100,100,100,100,100,100,100,100,100,100,100,100]])

array([0.97])